import { providerStyle } from "@/lib/providers";
import { BARGE, LIGHTHOUSE, SEA, SMOKE, TUG } from "./art";

/**
 * The footer's sea, drawn as a hand-tinted engraving: ink linework and
 * hatching (generated by scripts/generate-footer-art.py) over light washes of
 * colour. A steam tug hauls a barge across, left to right, over and over,
 * trailing billowing smoke; its three containers are the three newest releases. Server-rendered
 * SVG + CSS animation, no client JS.
 *
 * Scene coordinates: 290px tall, waterline at y = 212 — the sky above is
 * headroom for the smoke.
 */

export type Cargo = { name: string; provider: string };

const INK = "#1f3a42";
const PAPER = "#f4ecdc";
const RED = "#c8553d";
const GOLD = "#e8b93a";
const WATERLINE = 212;
const TUG_X = 370;
const TUG_Y = WATERLINE - 104;
const BARGE_Y = WATERLINE - 74;
const SMOKE_X = TUG_X + TUG.smoke.x;
const SMOKE_Y = TUG_Y + TUG.smoke.y;

const line = { fill: "none", stroke: INK, strokeWidth: 1.3, strokeLinecap: "round", strokeLinejoin: "round" } as const;
const fine = { fill: "none", stroke: INK, strokeWidth: 0.6, strokeLinecap: "round" } as const;

/** Tile the engraved sea into a repeating background, built once at import. */
function tile(width: number, height: number, body: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${body}</svg>`;
  return `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;
}
const BACK_TILE = tile(
  600,
  48,
  `<g transform="translate(0 18)"><path d="${SEA.coastHatch}" fill="none" stroke="${INK}" stroke-width=".5" opacity=".55"/><path d="${SEA.coast}" fill="none" stroke="${INK}" stroke-width="1" opacity=".75"/><path d="${SEA.back}" fill="none" stroke="${INK}" stroke-width=".55" opacity=".6"/></g>`,
);
const FRONT_TILE = tile(
  600,
  90,
  `<path d="${SEA.body}" fill="${PAPER}"/><path d="${SEA.crest}" fill="none" stroke="${INK}" stroke-width="1.3" stroke-linecap="round"/><path d="${SEA.front}" fill="none" stroke="${INK}" stroke-width=".7" stroke-linecap="round"/>`,
);

function shortName(name: string) {
  return name.length > 11 ? `${name.slice(0, 10)}…` : name;
}

/** Container dressing: provider wash, logo disc and a stencilled name plate. */
function ContainerFace({ c, cargo, index }: { c: (typeof BARGE.containers)[number]; cargo?: Cargo; index: number }) {
  const style = cargo ? providerStyle(cargo.provider) : null;
  const wash = style?.color ?? ["#4f8fa0", RED, GOLD][index % 3];
  const light = style && style.color.toUpperCase() === "#E8E8ED";
  return (
    <>
      <rect x={c.x} y={c.y} width={c.w} height={c.h} fill={PAPER} />
      <rect x={c.x} y={c.y} width={c.w} height={c.h} fill={wash} opacity={0.5} />
      {style && cargo && (
        <g>
          <circle cx={c.x + 16} cy={c.y + 22} r={10} fill="#fff" stroke={INK} strokeWidth={1.1} />
          {style.logoPath ? (
            <svg x={c.x + 9.5} y={c.y + 15.5} width={13} height={13} viewBox="0 0 24 24">
              <path d={style.logoPath} fill={light ? INK : style.color} />
            </svg>
          ) : (
            <text x={c.x + 16} y={c.y + 26} textAnchor="middle" fontSize={11} fontWeight={900} fill={light ? INK : style.color}>
              {style.initials}
            </text>
          )}
          <rect x={c.x + 29} y={c.y + 15} width={56} height={14} rx={1} fill={PAPER} stroke={INK} strokeWidth={0.8} />
          <text x={c.x + 57} y={c.y + 25} textAnchor="middle" className="ft-plate">
            {shortName(cargo.name)}
          </text>
        </g>
      )}
    </>
  );
}

/** The tug's bulwark — the solid band between deck edge and rail. Same sheer curve the generator uses. */
const BULWARK = (() => {
  const sheer = (x: number) => 80 - 24 * Math.pow((x - 10) / 202, 1.7);
  const xs = Array.from({ length: 26 }, (_, i) => 14 + i * 7.8);
  const top = xs.map((x) => `${x.toFixed(1)} ${(sheer(x) - 7).toFixed(1)}`);
  const bottom = [...xs].reverse().map((x) => `${x.toFixed(1)} ${(sheer(x) + 1).toFixed(1)}`);
  return `M${top.join("L")}L${bottom.join("L")}Z`;
})();

function Tug() {
  const w = TUG.washes;
  return (
    <g transform={`translate(${TUG_X} ${TUG_Y})`}>
      {/* An opaque paper base under every solid part, so nothing behind the
          tug shows through; the tints go on top of it. */}
      <g fill={PAPER}>
        <path d={w.hull} />
        <path d={w.boot} />
        <path d={w.bottom} />
        <path d={BULWARK} />
        <rect x={42} y={36} width={114} height={5} />
        <rect x={106} y={8} width={62} height={5} />
      </g>
      <path d={w.hull} fill="#2d5f6b" opacity={0.24} />
      <path d={BULWARK} fill="#2d5f6b" opacity={0.12} />
      <path d={w.boot} fill={RED} opacity={0.7} />
      <path d={w.bottom} fill="#3a4a4f" opacity={0.35} />
      <path d={w.house} fill={PAPER} />
      <path d={w.wheelhouse} fill={PAPER} />
      <path d={w.funnel} fill={GOLD} />
      <path d={w.funnelTop} fill={INK} />
      <path d={w.funnelBand} fill={PAPER} />
      <path d={w.buoy} fill={RED} opacity={0.8} />
      <path d={w.pennant} fill={RED} opacity={0.85} />
      <path d={TUG.fine} {...fine} />
      <path d={TUG.ink} {...line} />
      <path d={TUG.heavy} fill="none" stroke={INK} strokeWidth={2.4} strokeLinecap="round" />
      <path d={TUG.fenders} fill="none" stroke={INK} strokeWidth={2} />
      <text x={136} y={95} className="ft-plate ft-hull-name">
        TRACKAI
      </text>
      {/* Bow spray and wake: the foam strokes run, so the tug reads as under way. */}
      <path className="ft-foam" d="M214 99q10 -3 16 -12M212 101q14 -1 24 -8M210 103q16 2 28 -2" {...fine} strokeWidth={1} />
      <path className="ft-foam ft-foam-slow" d="M8 102q-30 -4 -64 0M6 105q-26 2 -52 6M10 99q-20 -6 -40 -6" {...fine} strokeWidth={1} />
    </g>
  );
}

function Barge({ cargo }: { cargo: Cargo[] }) {
  return (
    <g transform={`translate(0 ${BARGE_Y})`}>
      <path d={BARGE.washes.hull} fill={PAPER} />
      <path d={BARGE.washes.hull} fill="#3a4a4f" opacity={0.26} />
      {BARGE.containers.map((c, i) => (
        <ContainerFace key={c.x} c={c} cargo={cargo[i]} index={i} />
      ))}
      <path d={BARGE.fine} {...fine} />
      <path d={BARGE.ink} {...line} />
      <path className="ft-foam" d="M336 71q8 -2 12 -8M334 74q10 0 18 -5" {...fine} strokeWidth={1} />
    </g>
  );
}

function Lighthouse() {
  const w = LIGHTHOUSE.washes;
  return (
    <svg className="ft-lighthouse" width={208} height={176} viewBox="0 -12 260 220" aria-hidden="true">
      <path d={w.rock} fill="#8d8a80" opacity={0.3} />
      <path d={w.cottage} fill={PAPER} />
      <path d={w.roof} fill={RED} opacity={0.6} />
      <path d={w.tower} fill={PAPER} />
      <path d={w.bands} fill={RED} opacity={0.75} />
      <path d={w.lamp} className="ft-lamp" fill="#f5d06a" />
      <path d={LIGHTHOUSE.fine} {...fine} />
      <path d={LIGHTHOUSE.ink} {...line} />
      <path d={LIGHTHOUSE.surf} className="ft-foam ft-foam-slow" {...fine} />
    </svg>
  );
}

/** Smoke puffs: each rises from the funnel, swells, rolls back over the barge and thins out. */
const PUFFS = Array.from({ length: 14 }, (_, k) => ({
  k,
  variant: (k * 3) % SMOKE.length,
  delay: -k * 0.5,
  drift: k % 2 === 0 ? "ft-puff-a" : "ft-puff-b",
}));

export function FooterScene({ cargo }: { cargo: Cargo[] }) {
  return (
    <div className="ft-sea" aria-hidden="true">
      {/* Smoke billow shapes, defined once and reused by every puff. */}
      <svg width={0} height={0} className="absolute">
        <defs>
          {SMOKE.map((b, i) => (
            <symbol key={i} id={`ft-billow-${i}`} viewBox={`0 0 ${b.w} ${b.h}`} overflow="visible">
              <path d={b.fill} fill="#fbf8f1" />
              <path d={b.shade} fill="none" stroke={INK} strokeWidth={0.7} strokeLinecap="round" />
              <path d={b.line} fill="none" stroke={INK} strokeWidth={1.2} strokeLinecap="round" />
            </symbol>
          ))}
        </defs>
      </svg>

      <div className="ft-back" style={{ backgroundImage: BACK_TILE }} />
      <Lighthouse />

      <div className="ft-convoy">
        <div className="ft-smoke" style={{ left: SMOKE_X, top: SMOKE_Y }}>
          {PUFFS.map((p) => (
            <svg
              key={p.k}
              className={`ft-puff ${p.drift}`}
              viewBox={`0 0 ${SMOKE[p.variant].w} ${SMOKE[p.variant].h}`}
              style={{ animationDelay: `${p.delay}s` }}
            >
              <use href={`#ft-billow-${p.variant}`} />
            </svg>
          ))}
        </div>
        <svg className="ft-convoy-art" width={610} height={290} viewBox="0 0 610 290" overflow="visible">
          <Barge cargo={cargo} />
          <path
            d={`M334 ${BARGE_Y + 60}Q${(334 + TUG_X + TUG.towHook.x) / 2} ${BARGE_Y + 76} ${TUG_X + TUG.towHook.x} ${TUG_Y + TUG.towHook.y}`}
            fill="none"
            stroke={INK}
            strokeWidth={1.4}
          />
          <Tug />
        </svg>
      </div>

      <div className="ft-front" style={{ backgroundImage: FRONT_TILE, top: WATERLINE }} />
    </div>
  );
}
